# Generated by Django 3.0.4 on 2020-03-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jumia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('old_price', models.CharField(max_length=100)),
                ('total_ratings', models.CharField(max_length=100)),
                ('avg_rating', models.CharField(max_length=100)),
                ('new_price', models.CharField(max_length=100)),
                ('discount_percentage', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('discount', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
